/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProviderDashboardRouteImport } from './routes/provider-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCategoryIdRouteImport } from './routes/services.$categoryId'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers.$providerId'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ServicesServiceIdProvidersRouteImport } from './routes/services.$serviceId.providers'
import { Route as ProvidersProviderIdBookRouteImport } from './routes/providers.$providerId.book'
import { Route as AdminProvidersIdRouteImport } from './routes/admin.providers.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/provider-dashboard',
  path: '/provider-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCategoryIdRoute = ServicesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => ServicesRoute,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdProvidersRoute =
  ServicesServiceIdProvidersRouteImport.update({
    id: '/$serviceId/providers',
    path: '/$serviceId/providers',
    getParentRoute: () => ServicesRoute,
  } as any)
const ProvidersProviderIdBookRoute = ProvidersProviderIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ProvidersProviderIdRoute,
} as any)
const AdminProvidersIdRoute = AdminProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/providers/$providerId': typeof ProvidersProviderIdRouteWithChildren
  '/services/$categoryId': typeof ServicesCategoryIdRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/providers/$providerId/book': typeof ProvidersProviderIdBookRoute
  '/services/$serviceId/providers': typeof ServicesServiceIdProvidersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/providers/$providerId': typeof ProvidersProviderIdRouteWithChildren
  '/services/$categoryId': typeof ServicesCategoryIdRoute
  '/services': typeof ServicesIndexRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/providers/$providerId/book': typeof ProvidersProviderIdBookRoute
  '/services/$serviceId/providers': typeof ServicesServiceIdProvidersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin_/login': typeof AdminLoginRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/providers/$providerId': typeof ProvidersProviderIdRouteWithChildren
  '/services/$categoryId': typeof ServicesCategoryIdRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/providers/$id': typeof AdminProvidersIdRoute
  '/providers/$providerId/book': typeof ProvidersProviderIdBookRoute
  '/services/$serviceId/providers': typeof ServicesServiceIdProvidersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/login'
    | '/provider-dashboard'
    | '/services'
    | '/admin/login'
    | '/customer/profile'
    | '/providers/$providerId'
    | '/services/$categoryId'
    | '/services/'
    | '/admin/providers/$id'
    | '/providers/$providerId/book'
    | '/services/$serviceId/providers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/login'
    | '/provider-dashboard'
    | '/admin/login'
    | '/customer/profile'
    | '/providers/$providerId'
    | '/services/$categoryId'
    | '/services'
    | '/admin/providers/$id'
    | '/providers/$providerId/book'
    | '/services/$serviceId/providers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/login'
    | '/provider-dashboard'
    | '/services'
    | '/admin_/login'
    | '/customer/profile'
    | '/providers/$providerId'
    | '/services/$categoryId'
    | '/services/'
    | '/admin/providers/$id'
    | '/providers/$providerId/book'
    | '/services/$serviceId/providers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-dashboard': {
      id: '/provider-dashboard'
      path: '/provider-dashboard'
      fullPath: '/provider-dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$categoryId': {
      id: '/services/$categoryId'
      path: '/$categoryId'
      fullPath: '/services/$categoryId'
      preLoaderRoute: typeof ServicesCategoryIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId/providers': {
      id: '/services/$serviceId/providers'
      path: '/$serviceId/providers'
      fullPath: '/services/$serviceId/providers'
      preLoaderRoute: typeof ServicesServiceIdProvidersRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/providers/$providerId/book': {
      id: '/providers/$providerId/book'
      path: '/book'
      fullPath: '/providers/$providerId/book'
      preLoaderRoute: typeof ProvidersProviderIdBookRouteImport
      parentRoute: typeof ProvidersProviderIdRoute
    }
    '/admin/providers/$id': {
      id: '/admin/providers/$id'
      path: '/providers/$id'
      fullPath: '/admin/providers/$id'
      preLoaderRoute: typeof AdminProvidersIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProvidersIdRoute: typeof AdminProvidersIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProvidersIdRoute: AdminProvidersIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesRouteChildren {
  ServicesCategoryIdRoute: typeof ServicesCategoryIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesServiceIdProvidersRoute: typeof ServicesServiceIdProvidersRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryIdRoute: ServicesCategoryIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesServiceIdProvidersRoute: ServicesServiceIdProvidersRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ProvidersProviderIdRouteChildren {
  ProvidersProviderIdBookRoute: typeof ProvidersProviderIdBookRoute
}

const ProvidersProviderIdRouteChildren: ProvidersProviderIdRouteChildren = {
  ProvidersProviderIdBookRoute: ProvidersProviderIdBookRoute,
}

const ProvidersProviderIdRouteWithChildren =
  ProvidersProviderIdRoute._addFileChildren(ProvidersProviderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  ProvidersProviderIdRoute: ProvidersProviderIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
