/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProviderDashboardRouteImport } from './routes/provider-dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesCategoryIdRouteImport } from './routes/services.$categoryId'
import { Route as ProvidersServiceIdRouteImport } from './routes/providers.$serviceId'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ProvidersProviderIdBookRouteImport } from './routes/providers.$providerId.book'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderDashboardRoute = ProviderDashboardRouteImport.update({
  id: '/provider-dashboard',
  path: '/provider-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryIdRoute = ServicesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => ServicesRoute,
} as any)
const ProvidersServiceIdRoute = ProvidersServiceIdRouteImport.update({
  id: '/providers/$serviceId',
  path: '/providers/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersProviderIdBookRoute = ProvidersProviderIdBookRouteImport.update({
  id: '/providers/$providerId/book',
  path: '/providers/$providerId/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/providers/$serviceId': typeof ProvidersServiceIdRoute
  '/services/$categoryId': typeof ServicesCategoryIdRoute
  '/providers/$providerId/book': typeof ProvidersProviderIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/providers/$serviceId': typeof ProvidersServiceIdRoute
  '/services/$categoryId': typeof ServicesCategoryIdRoute
  '/providers/$providerId/book': typeof ProvidersProviderIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/provider-dashboard': typeof ProviderDashboardRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin_/login': typeof AdminLoginRoute
  '/providers/$serviceId': typeof ProvidersServiceIdRoute
  '/services/$categoryId': typeof ServicesCategoryIdRoute
  '/providers/$providerId/book': typeof ProvidersProviderIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/provider-dashboard'
    | '/services'
    | '/admin/login'
    | '/providers/$serviceId'
    | '/services/$categoryId'
    | '/providers/$providerId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/provider-dashboard'
    | '/services'
    | '/admin/login'
    | '/providers/$serviceId'
    | '/services/$categoryId'
    | '/providers/$providerId/book'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/provider-dashboard'
    | '/services'
    | '/admin_/login'
    | '/providers/$serviceId'
    | '/services/$categoryId'
    | '/providers/$providerId/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ProviderDashboardRoute: typeof ProviderDashboardRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ProvidersServiceIdRoute: typeof ProvidersServiceIdRoute
  ProvidersProviderIdBookRoute: typeof ProvidersProviderIdBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-dashboard': {
      id: '/provider-dashboard'
      path: '/provider-dashboard'
      fullPath: '/provider-dashboard'
      preLoaderRoute: typeof ProviderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$categoryId': {
      id: '/services/$categoryId'
      path: '/$categoryId'
      fullPath: '/services/$categoryId'
      preLoaderRoute: typeof ServicesCategoryIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/providers/$serviceId': {
      id: '/providers/$serviceId'
      path: '/providers/$serviceId'
      fullPath: '/providers/$serviceId'
      preLoaderRoute: typeof ProvidersServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$providerId/book': {
      id: '/providers/$providerId/book'
      path: '/providers/$providerId/book'
      fullPath: '/providers/$providerId/book'
      preLoaderRoute: typeof ProvidersProviderIdBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesCategoryIdRoute: typeof ServicesCategoryIdRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryIdRoute: ServicesCategoryIdRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ProviderDashboardRoute: ProviderDashboardRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ProvidersServiceIdRoute: ProvidersServiceIdRoute,
  ProvidersProviderIdBookRoute: ProvidersProviderIdBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
